name: 'maven-webgoat'
on:
  push:
    branches:
      - "**"
  pull_request:
    types: 
      - closed
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
  security-events: write # Required for uploading code scanning.

jobs:
 mvn-build-and-publish:
   runs-on: ubuntu-latest
   env:
     BUILD_NAME: 'maven-webgoat'
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
        java-version: '17'
        distribution: 'temurin'
     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v4
       env:
        JF_URL: ${{ vars.JF_URL }}
       with:
        oidc-provider-name: mpatel-git
     - name: Health check JFrog Artifactory instance 🐸
       run: |
        jf --version
        jf rt ping
        jf mvnc --repo-resolve-releases alpha-mvn-virtual --repo-resolve-snapshots alpha-mvn-virtual --repo-deploy-releases alpha-mvn-virtual --repo-deploy-snapshots alpha-mvn-virtual
     - name: Fix Code Formatting with Spotless
       run: mvn spotless:apply
     - name: Curation Audit
       run: |
        jf ca --format=table --threads=100
     - name: Build Maven Package
       run: |
        jf mvn clean install -f pom.xml -Dmaven.test.skip=true -Dartifactory.publish.artifacts=true --build-name ${{env.BUILD_NAME}} --build-number ${{github.run_number}}
     - name: Security Audit
       run: |
        jf audit
     - name: Login to JFrog Docker repo
       uses: docker/login-action@v3
       with:
        registry: ${{ secrets.JF_URL }}
        username: ${{ secrets.JF_USER }}
        password: ${{ secrets.JF_PASSWORD }}
     - name: Docker Build 🐳🐸 and scan
       run: |
         jf docker build . -t soleng.jfrog.io/alpha-mvn-virtual/webgoat-maven:${{github.run_number}}
         jf docker scan soleng.jfrog.io/alpha-mvn-virtual/webgoat-maven:${{github.run_number}}
         jf docker push soleng.jfrog.io/alpha-mvn-virtual/webgoat-maven:${{github.run_number}}
     - name: Publish build build-info
       run: |
         # Collect and store environment variables in the build-info
         jf rt bce ${{env.BUILD_NAME}} ${{github.run_number}}
         # Collect and store VCS details in the build-info
         jf rt bag ${{env.BUILD_NAME}} ${{github.run_number}}
         # Publish the build-info to Artifactory
         jf rt bp ${{env.BUILD_NAME}} ${{github.run_number}}
         # Scan the published build-info with Xray
         jf rt bs ${{env.BUILD_NAME}} ${{github.run_number}}
